major_changes:
- elb_application_lb - The module has been migrated from the ``community.aws`` collection.
  Playbooks using the Fully Qualified Collection Name for this module should be updated
  to use ``amazon.aws.elb_application_lb``.
- elb_application_lb_info - The module has been migrated from the ``community.aws``
  collection. Playbooks using the Fully Qualified Collection Name for this module
  should be updated to use ``amazon.aws.elb_application_lb_info``.
