---
name: Collection Docs
concurrency:
  group: docs-${{ github.head_ref }}
  cancel-in-progress: true
on:
  pull_request_target:
    types: [opened, synchronize, reopened, closed]
env:
  GHP_BASE_URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}

jobs:
  validate-docs:
    permissions:
      contents: read
    name: Validate Ansible Docs
    uses: ansible-community/github-docs-build/.github/workflows/_shared-docs-build-pr.yml@main
    with:
      init-lenient: false
      init-fail-on-error: true
      ansible-ref: devel
      intersphinx-links: |
        community_aws:https://ansible-collections.github.io/community.aws/branch/main/
        ansible_devel:https://docs.ansible.com/ansible-core/devel/
      artifact-name: ${{ github.event.repository.name }}_validate_docs_${{ github.event.pull_request.head.sha }}


  build-docs:
    permissions:
      contents: read
    name: Build Ansible Docs
    uses: ansible-community/github-docs-build/.github/workflows/_shared-docs-build-pr.yml@main
    with:
      init-lenient: true
      init-fail-on-error: false
      ansible-ref: devel
      intersphinx-links: |
        community_aws:https://ansible-collections.github.io/community.aws/branch/main/
        ansible_devel:https://docs.ansible.com/ansible-core/devel/

  comment:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    needs: [build-docs]
    name: PR comments
    steps:
      - name: PR comment
        uses: ansible-community/github-docs-build/actions/ansible-docs-build-comment@main
        with:
          body-includes: "## Docs Build"
          reactions: heart
          action: ${{ needs.build-docs.outputs.changed != 'true' && 'remove' || '' }}
          on-closed-action: remove
          on-merged-body: |
            ## Docs Build üìù

            Thank you for contribution!‚ú®

            This PR has been merged and your docs changes will be incorporated when they are next published.
          body: |
            ## Docs Build üìù

            Thank you for contribution!‚ú®

            The docsite for **this PR** is available for download as an artifact from this run:
            ${{ needs.build-docs.outputs.artifact-url }}

            You can compare to the docs for the `main` branch here:
            ${{ env.GHP_BASE_URL }}/branch/main

            File changes:

            ${{ needs.build-docs.outputs.diff-files-rendered }}

            ${{ needs.build-docs.outputs.diff-rendered }}
