---
name: Generate GitHub Release (manual trigger)
concurrency:
  group: release-${{ github.head_ref }}
  cancel-in-progress: true
on:
  workflow_dispatch:
    inputs:
      release:
        required: true
        description: Release to generate
        type: string

jobs:
  generate-release-log:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Generate Release Log
        uses: ansible-collections/amazon.aws/.github/actions/ansible_release_log@main
        with:
          release: ${{ inputs.release }}

  perform-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs:
      - generate-release-log
    steps:
      - name: Generate Release
        uses: ansible-collections/amazon.aws/.github/actions/ansible_release_tag@main
        with:
          release: ${{ inputs.release }}
          collection-name: amazon.aws
