---
name: sanity tests

on: [workflow_call] # allow this workflow to be called from other workflows

jobs:
  sanity:
    uses: ansible-network/github_actions/.github/workflows/sanity.yml@main
    with:
      matrix_exclude: >-
          [
            {
              "ansible-version": "stable-2.16"
            }
          ]
